type: remap
inputs:
  - parse_json_kubernetes_audit_logs
source: |
  del(.kind)

  .event.id = .auditID
  .event.action = join!(compact([.objectRef.resource, .objectRef.subresource, .verb]), ".")
  .event.outcome = if .annotations."authorization.k8s.io/decision" == "allow" { "success" } else { "failure" }
  .event.dataset = "kubernetes.audit"

  .user_agent.original = .userAgent
  .user.name = .user.username
  .source.ip = .sourceIPs[0]

  .orchestrator.type = "$${KUBERNETES_CLUSTER_TYPE}"
  .orchestrator.cluster.name = "$${KUBERNETES_CLUSTER_NAME}"
  .orchestrator.namespace = .objectRef.namespace
  .orchestrator.resource.type = .objectRef.resource
  .orchestrator.resource.name = .objectRef.name

  .kubernetes.audit = .
