type: remap
inputs:
  - parse_json_kubernetes_audit_logs
source: |
  .kubernetes.audit.annotations = .annotations
  .kubernetes.audit.auditID = .auditID
  .kubernetes.audit.authenticationMetadata = .authenticationMetadata
  .kubernetes.audit.impersonatedUser = .impersonatedUser
  .kubernetes.audit.level = .level
  .kubernetes.audit.objectRef = .objectRef
  .kubernetes.audit.requestReceivedTimestamp = .requestReceivedTimestamp
  .kubernetes.audit.requestURI = .requestURI
  .kubernetes.audit.responseStatus = .responseStatus
  .kubernetes.audit.sourceIPs = .sourceIPs
  .kubernetes.audit.stage = .stage
  .kubernetes.audit.stageTimestamp = .stageTimestamp
  .kubernetes.audit.user = .user
  .kubernetes.audit.userAgent = .userAgent
  .kubernetes.audit.verb = .verb

  .timestamp = .requestReceivedTimestamp

  .event.id = .auditID
  .event.action = join!(compact([.objectRef.resource, .objectRef.subresource, .verb]), ".")
  .event.outcome = if .annotations."authorization.k8s.io/decision" == "allow" { "success" } else { "failure" }
  .event.dataset = "kubernetes.audit"

  .user_agent.original = .userAgent
  .user.name = .user.username
  .user.roles = .user.groups
  .source.ip = .sourceIPs[0]

  .orchestrator.type = "$${KUBERNETES_CLUSTER_TYPE}"
  .orchestrator.cluster.name = "$${KUBERNETES_CLUSTER_NAME}"
  .orchestrator.namespace = .objectRef.namespace
  .orchestrator.resource.type = .objectRef.resource
  .orchestrator.resource.name = .objectRef.name

  del(.annotations)
  del(.auditID)
  del(.authenticationMetadata)
  del(.impersonatedUser)
  del(.kind)
  del(.level)
  del(.objectRef)
  del(.requestReceivedTimestamp)
  del(.requestURI)
  del(.responseStatus)
  del(.sourceIPs)
  del(.stage)
  del(.stageTimestamp)
  del(.user.extra)
  del(.user.groups)
  del(.user.uid)
  del(.user.username)
  del(.userAgent)
  del(.verb)
