type: remap
inputs:
  - tag_stream_unifi_logs
source: |
  parsed, err = parse_syslog(._raw)
  if err == null {
    . = merge(., parsed)
  } else {
    .message = ._raw
  }

  if .appname == "CEF" {
    parsed, err = parse_cef(join!(["CEF", .message], separator: ":"))
    if err == null {
      . = merge(., parsed)
    } else {
      .@vector.parse_error = err
    }
  }
