type: route
inputs:
  - vector_agents
  - tag_source_unifi_logs
route:
  kubernetes_audit_logs:
    type: vrl
    source: .@vector.source == "kubernetes.audit"
  kubernetes_container_logs:
    type: vrl
    source: .@vector.source == "kubernetes.container"
  kubernetes_flow_logs:
    type: vrl
    source: .@vector.source == "kubernetes.flow"
  unifi_logs:
    type: vrl
    source: .@vector.source == "unifi"
