type: remap
inputs:
  - normalize_kubernetes_flow_logs
source: |
  type = "logs"
  dataset = "kubernetes.container"
  namespace = .kubernetes.pod_namespace

  .data_stream.type = type
  .data_stream.dataset = dataset
  .data_stream.namespace = namespace
