type: remap
inputs:
  - parse_cef_unifi_logs
source: |
  type = "logs"
  dataset = "unifi"
  namespace = "default"

  .data_stream.type = type
  .data_stream.dataset = dataset
  .data_stream.namespace = namespace
