type: route
inputs:
  - parse_json
  - parse_unifi
route:
  kubernetes_audit_logs:
    type: vrl
    source: .@vector.stream == "logs.kubernetes.audit"
  kubernetes_container_logs:
    type: vrl
    source: .@vector.stream == "logs.kubernetes.container"
  kubernetes_flow_logs:
    type: vrl
    source: .@vector.stream == "logs.kubernetes.flow"
  kubernetes_host_metrics:
    type: vrl
    source: .@vector.stream == "metrics.kubernetes.host"
  unifi_logs:
    type: vrl
    source: .@vector.stream == "logs.unifi"
