type: remap
inputs:
  - parse_json_kubernetes_container_logs
source: |
  type = "logs"
  dataset = "kubernetes.container"
  namespace = "default"

  .data_stream.type = type
  .data_stream.dataset = dataset
  .data_stream.namespace = namespace
