type: remap
inputs:
  - vector_aggregator_metrics
source: |
  .tags."@vector.stream" = "metrics.vector.aggregator"
  .tags."kubernetes.cluster" = "$${KUBERNETES_CLUSTER_NAME}"
  .tags.host = "$${VECTOR_SELF_NODE_NAME}"
  .tags.role = "aggregator"
