type: remap
inputs:
  - route_parsed_streams.vector_aggregator_metrics
source: |
  .tags."data_stream.type" = "metrics"
  .tags."data_stream.dataset" = "vector.aggregator"
  .tags."data_stream.namespace" = "default"
