type: remap
inputs:
  - route_parsed_streams.kubernetes_host_metrics
source: |
  .tags."data_stream.type" = "metrics"
  .tags."data_stream.dataset" = "kubernetes.host"
  .tags."data_stream.namespace" = "default"
