apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yml
  - helmrelease.yml

configMapGenerator:
  - name: vector-aggregator-values
    files:
      - values.yml

  - name: vector-aggregator-config
    files:
      - ../../../vector/aggregator/sources.yml
      - ../../../vector/aggregator/transforms.yml
      - ../../../vector/aggregator/sinks.yml

generatorOptions:
  disableNameSuffixHash: true
