type: host_metrics
collectors:
  - cpu
  - disk
  - filesystem
  - host
  - load
  - memory
  - network
  - process
namespace: host
scrape_interval_secs: 30
filesystem:
  devices:
    excludes: ["binfmt_misc"]
