apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-ca
  namespace: vector
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDVjCCAj6gAwIBAgIRAOe+q0DDwPFOc0QBwJhkpoMwDQYJKoZIhvcNAQELBQAw
    NTEWMBQGA1UECxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJj
    aC1odHRwMB4XDTI2MDcyOTAyMDczNVoXDTI3MDcyOTAyMTczNVowNTEWMBQGA1UE
    CxMNZWxhc3RpY3NlYXJjaDEbMBkGA1UEAxMSZWxhc3RpY3NlYXJjaC1odHRwMIIB
    IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8vdQAi349S2xsSMrUPqOTAoh
    abyL0+W0OYnV7CkJm2+MGQgpRiPZp/C2wehIFhEUSrgztSUYIUyYMRdYq8WBB9E/
    uTZK1/VSGNOML2ShE8aoxWIFSQQEZ6zvqa+8CIDQi0OK+bv35NbcKAx/I2075Dfe
    VnYUAl1UPDTWP0j+UQ8YT7+mWH5xxswPwk2mGMoFArCuxgaDcc5rsSZ8Zr3Q8AbE
    nLWOKyekGdF8VK6BLX53jWECVZy6a94JBxvhgtL6A4uX/0pZPvZ+I6+jgujDbckL
    3ONPUG61Qmf2tTN/GqD0/DI2gI0ypaJYooTm/zrtYm5mukUXBBYbquDZPHjsCQID
    AQABo2EwXzAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsG
    AQUFBwMCMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFN7nygDM4blbw0SGae8b
    RXOf671RMA0GCSqGSIb3DQEBCwUAA4IBAQBJxRFgA6p5cxSNsXL28X0UtaKQROlS
    uM3aFBcpyB3w4N4ZoU9sBag2TnO73ce1+yudSLWgb0mMj/yqHXaHeBYqnM7R22wX
    WZgSNCPmZLHi+yDNpigqq6Lp/lDahP731ohLsi0YZuX/wUKZCdWhWKTiiHYP7HVX
    Q7I82zrucHv8Cf8rAJflpMqJSa8ShWmCMrcAmjx1T7GVmkkz8ZpRNxIFVU8/nrB5
    ma7FiqmYLWBl7rpeZrKHaSGL9CkJXKW6j3051GGszmzueJ039DsQnILdwTvqMSbb
    pBn0SBKNNLNIWn74wQCNDzi/VnTgavwR4nMni3sxZepXDzMDODSAQ1iv
    -----END CERTIFICATE-----
