apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent
  - aggregator
  - elastic-ca.yml
  - helmrepository.yml
  - secretstore.yml
  - udproutes.yml

configMapGenerator:
  - name: vector-base
    files:
      - ../../config/vector.yml

  - name: vector-agent-sources
    files:
      - ../../config/agent/sources/kubernetes_audit_logs.yml
      - ../../config/agent/sources/kubernetes_container_logs.yml
      - ../../config/agent/sources/kubernetes_flow_logs.yml

  - name: vector-agent-transforms
    files:
      - ../../config/agent/transforms/tag_source_kubernetes_audit_logs.yml
      - ../../config/agent/transforms/tag_source_kubernetes_container_logs.yml
      - ../../config/agent/transforms/tag_source_kubernetes_flow_logs.yml

  - name: vector-agent-sinks
    files:
      - ../../config/agent/sinks/vector_aggregator.yml

  - name: vector-aggregator-sources
    files:
      - ../../config/aggregator/sources/unifi_logs.yml
      - ../../config/aggregator/sources/vector_agents.yml

  - name: vector-aggregator-transforms
    files:
      - ../../config/aggregator/transforms/normalize_kubernetes_audit_logs.yml
      - ../../config/aggregator/transforms/normalize_kubernetes_flow_logs.yml
      - ../../config/aggregator/transforms/parse_json_kubernetes_audit_logs.yml
      - ../../config/aggregator/transforms/parse_json_kubernetes_container_logs.yml
      - ../../config/aggregator/transforms/parse_json_kubernetes_flow_logs.yml
      - ../../config/aggregator/transforms/parse_syslog_unifi_logs.yml
      - ../../config/aggregator/transforms/route_by_source.yml
      - ../../config/aggregator/transforms/route_elastic_data_stream_kubernetes_audit_logs.yml
      - ../../config/aggregator/transforms/route_elastic_data_stream_kubernetes_container_logs.yml
      - ../../config/aggregator/transforms/route_elastic_data_stream_kubernetes_flow_logs.yml
      - ../../config/aggregator/transforms/tag_source_unifi_logs.yml

  - name: vector-aggregator-sinks
    files:
      - ../../config/aggregator/sinks/elasticsearch_logs.yml

generatorOptions:
  disableNameSuffixHash: true
