apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent
  - aggregator
  - elastic-ca.yml
  - helmrepository.yml
  - secretstore.yml
  - udproutes.yml

configMapGenerator:
  - name: vector-base
    files:
      - ../../../vector/vector.yml

generatorOptions:
  disableNameSuffixHash: true
