type: elasticsearch
api_version: "v8"
inputs:
  - tag_elastic_data_stream_kubernetes_host_metrics
  # - tag_elastic_data_stream_vector_agent_metrics
  # - tag_elastic_data_stream_vector_aggregator_metrics
endpoints:
  - https://elasticsearch-es-http.elastic-stack.svc:9200
tls:
  ca_file: /etc/ssl/elastic/ca.crt
auth:
  strategy: basic
  user: "$${ELASTIC_USERNAME}"
  password: "$${ELASTIC_PASSWORD}"
mode: data_stream
dangerously_allow_unconfined_template_resolution: true
data_stream:
  type: '{{ .tags."data_stream.type" }}'
  dataset: '{{ .tags."data_stream.dataset" }}'
  namespace: '{{ .tags."data_stream.namespace" }}'
bulk:
  action: create
compression: gzip
batch:
  max_bytes: 10485760 # ~10MB
  max_events: 20000
  timeout_secs: 1
