apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elastic-credentials
  namespace: vector
spec:
  secretStoreRef:
    name: vector-vault
    kind: SecretStore
  refreshPolicy: Periodic
  refreshInterval: "1h0m0s"
  target:
    name: vector-elastic-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: vector/elastic_user
        property: username
    - secretKey: password
      remoteRef:
        key: vector/elastic_user
        property: password
