apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vector-agent
  namespace: vector
spec:
  serviceAccountName: flux
  targetNamespace: vector
  interval: 30m
  chart:
    spec:
      chart: vector
      version: "0.57.x"
      sourceRef:
        kind: HelmRepository
        name: vector
      interval: 12h
  releaseName: vector-agent
  valuesFrom:
    - kind: ConfigMap
      name: vector-agent-values
      valuesKey: values.yml
