apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yml
  - helmrelease.yml

configMapGenerator:
  - name: vector-agent-values
    files:
      - values.yml

generatorOptions:
  disableNameSuffixHash: true
