apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certificate.yml
  - helmrelease.yml

configMapGenerator:
  - name: vector-agent-values
    files:
      - values.yml

  - name: vector-agent-config
    files:
      - ../../vector/agent/sources.yml
      - ../../vector/agent/transforms.yml
      - ../../vector/agent/sinks.yml

generatorOptions:
  disableNameSuffixHash: true
