name: Vector Pipeline Tests

on:
  pull_request:
    paths:
      - config/**
      - tests/**

jobs:
  test:
    name: Test ${{ matrix.component }} Configuration
    runs-on: ubuntu-latest
    container:
      image: timberio/vector:nightly-alpine
    strategy:
      fail-fast: false
      matrix:
        component: [agent, aggregator]

    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.0.0

      - name: Validate Configuration
        run: |
          vector validate
            --config-dir config/${{ matrix.component }}/ \
            --no-environment

      - name: Run Unit Tests
        run: |
          vector test \
            --config-dir config/${{ matrix.component }} \
            --config-dir tests/${{ matrix.component }}

          vector test \
            --config-dir config/${{ matrix.component }} \
            --config-dir tests/${{ matrix.component }}
